version: 2
updates:
- package-ecosystem: bundler
  directory: "/ruby-gem"
  schedule:
    interval: weekly
    time: "01:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 99
- package-ecosystem: npm
  directory: "/ruby-gem/spec/dummy"
  schedule:
    interval: weekly
    time: "01:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 99
- package-ecosystem: npm
  directory: "/npm-api-maker"
  schedule:
    interval: weekly
    time: "01:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 99
- package-ecosystem: bundler
  directory: "/api_maker_table_rubygem"
  schedule:
    interval: weekly
    time: "01:00"
    timezone: Europe/Berlin
