version: 2
updates:
- package-ecosystem: bundler
  directory: "/ruby-gem"
  schedule:
    interval: daily
    time: "01:00"
    timezone: Europe/Copenhagen
  open-pull-requests-limit: 99
- package-ecosystem: bundler
  directory: "/ruby-gem/spec/dummy"
  schedule:
    interval: daily
    time: "01:00"
    timezone: Europe/Copenhagen
  open-pull-requests-limit: 99
- package-ecosystem: npm
  directory: "/ruby-gem/spec/dummy"
  schedule:
    interval: daily
    time: "01:00"
    timezone: Europe/Copenhagen
  open-pull-requests-limit: 99
- package-ecosystem: npm
  directory: "/npm-api-maker"
  schedule:
    interval: daily
    time: "01:00"
    timezone: Europe/Copenhagen
  open-pull-requests-limit: 99
- package-ecosystem: npm
  directory: "/npm-api-maker-bootstrap"
  schedule:
    interval: daily
    time: "01:00"
    timezone: Europe/Copenhagen
  open-pull-requests-limit: 99
- package-ecosystem: npm
  directory: "/npm-api-maker-inputs"
  schedule:
    interval: daily
    time: "01:00"
    timezone: Europe/Copenhagen
  open-pull-requests-limit: 99
