import js from "@eslint/js"
import {defineConfig} from "eslint/config"
import expoConfig from "eslint-config-expo/flat.js"
import globals from "globals"
import jest from "eslint-plugin-jest"

export default defineConfig([
  expoConfig,
  jest.configs["flat/recommended"],
  js.configs.recommended,
  {
    ignores: ["dist/*"],
    languageOptions: {
      globals: {
        ...globals.jest
      }
    },
    rules: {
      "accessor-pairs": "error",
      "array-bracket-newline": "error",
      "array-bracket-spacing": "error",
      "array-callback-return": "error",
      "arrow-body-style": "error",
      "arrow-parens": "error",
      "arrow-spacing": "error",
      "block-scoped-var": "error",
      "block-spacing": "error",
      "brace-style": "off",
      "class-methods-use-this": "off",
      "comma-dangle": "error",
      "comma-spacing": "error",
      "comma-style": "error",
      "complexity": "error",
      "computed-property-spacing": "error",
      "consistent-return": "off",
      "consistent-this": "error",
      "curly": "off",
      "default-case": "error",
      "default-case-last": "error",
      "default-param-last": "error",
      "dot-location": ["error", "property"],
      "dot-notation": "error",
      "eol-last": "error",
      "eqeqeq": "off",
      "function-call-argument-newline": "off",
      "func-call-spacing": "error",
      "func-name-matching": "error",
      "func-style": "error",
      "function-paren-newline": "off",
      "generator-star-spacing": "error",
      "grouped-accessor-pairs": "error",
      "guard-for-in": "off", // Disabled because insane?
      "id-denylist": "error",
      "id-match": "error",
      "implicit-arrow-linebreak": "error",
      "indent": ["error", 2, {"MemberExpression": "off"}],
      "init-declarations": "off",
      "jest/max-expects": "error",
      "jest/max-nested-describe": "error",
      "jest/no-alias-methods": "error",
      "jest/no-conditional-in-test": "error",
      "jest/no-duplicate-hooks": "error",
      "jest/no-hooks": "off",
      "jest/no-large-snapshots": "error",
      "jest/no-restricted-matchers": "error",
      "jest/no-restricted-jest-methods": "error",
      "jest/no-test-return-statement": "error",
      "jest/prefer-comparison-matcher": "error",
      "jest/prefer-each": "error",
      "jest/prefer-equality-matcher": "error",
      "jest/prefer-expect-resolves": "off", // Needs configuration and no documentation could be found?
      "jest/prefer-hooks-on-top": "error",
      "jest/prefer-lowercase-title": "off",
      "jest/prefer-mock-promise-shorthand": "error",
      "prefer-object-has-own": "error",
      "jest/prefer-snapshot-hint": "error",
      "jest/prefer-to-be": "off", // Needs configuration and no documentation could be found?
      "jest/prefer-spy-on": "error",
      "jest/prefer-to-contain": "error",
      "jest/prefer-todo": "error",
      "jest/require-hook": "error",
      "jest/require-to-throw-message": "error",
      "jest/require-top-level-describe": "error",
      "jsx-quotes": "error",
      "key-spacing": "error",
      "keyword-spacing": "off",
      "linebreak-style": ["error", "unix"],
      "line-comment-position": "off",
      "lines-around-comment": ["error", {allowClassStart: true}],
      "lines-between-class-members": "off",
      "logical-assignment-operators": "error",
      "max-classes-per-file": "off",
      "max-depth": "error",
      "max-nested-callbacks": "error",
      "max-params": "error",
      "max-statements-per-line": "error",
      "multiline-ternary": "off",
      "new-cap": "error",
      "new-parens": "error",
      "newline-per-chained-call": "error",
      "no-alert": "error",
      "no-array-constructor": "error",
      "no-await-in-loop": "error",
      "no-bitwise": "error",
      "no-caller": "error",
      "no-confusing-arrow": "error",
      "no-constant-binary-expression": "error",
      "no-constant-condition": "off",
      "no-constructor-return": "error",
      "no-continue": "error",
      "no-div-regex": "error",
      "no-duplicate-imports": "error",
      "no-else-return": "off",
      "no-eq-null": "error",
      "no-eval": "error",
      "no-extra-bind": "error",
      "no-extra-label": "error",
      "no-extra-parens": "error",
      "no-floating-decimal": "error",
      "no-implicit-coercion": "error",
      "no-implicit-globals": "error",
      "no-implied-eval": "error",
      "no-inline-comments": "off",
      "no-invalid-this": "error",
      "no-iterator": "error",
      "no-label-var": "error",
      "no-labels": "error",
      "no-lone-blocks": "error",
      "no-lonely-if": "off",
      "no-loop-func": "error",
      "no-loss-of-precision": "error",
      "no-mixed-operators": "error",
      "no-multi-assign": "error",
      "no-multi-spaces": "error",
      "no-multi-str": "error",
      "no-multiple-empty-lines": "error",
      "no-negated-condition": "error",
      "no-nested-ternary": "error",
      "no-new": "error",
      "no-new-func": "error",
      "no-new-object": "error",
      "no-new-wrappers": "error",
      "no-nonoctal-decimal-escape": "error",
      "no-octal-escape": "error",
      "no-param-reassign": "error",
      "no-plusplus": "off",
      "no-promise-executor-return": "error",
      "no-proto": "error",
      "no-restricted-exports": "error",
      "no-restricted-globals": "error",
      "no-restricted-imports": "error",
      "no-restricted-properties": "error",
      "no-restricted-syntax": "error",
      "no-return-assign": "error",
      "no-return-await": "off",
      "no-script-url": "error",
      "no-self-compare": "error",
      "no-sequences": "error",
      "no-tabs": "error",
      "no-template-curly-in-string": "error",
      "no-ternary": "off",
      "no-throw-literal": "error",
      "no-trailing-spaces": "error",
      "no-undef-init": "error",
      "no-unmodified-loop-condition": "error",
      "no-unneeded-ternary": "error",
      "no-unreachable-loop": "error",
      "no-unused-private-class-members": "error",
      "no-unsafe-optional-chaining": "error",
      "no-unused-expressions": "error",
      "no-unused-vars": ["error", {"argsIgnorePattern": "^_", "ignoreRestSiblings": true}],
      "no-use-before-define": "error",
      "no-useless-backreference": "error",
      "no-useless-call": "error",
      "no-useless-computed-key": "error",
      "no-useless-concat": "error",
      "no-useless-constructor": "error",
      "no-useless-rename": "error",
      "no-useless-return": "error",
      "no-void": "error",
      "no-warning-comments": "off",
      "no-whitespace-before-property": "error",
      "nonblock-statement-body-position": ["error", "any"],
      "object-curly-newline": "error",
      "object-curly-spacing": "error",
      "object-shorthand": "error",
      "one-var-declaration-per-line": "error",
      "operator-assignment": "error",
      "operator-linebreak": "error",
      "padded-blocks": ["error", "never"],
      "padding-line-between-statements": "error",
      "prefer-arrow-callback": "error",
      "prefer-exponentiation-operator": "error",
      "prefer-numeric-literals": "error",
      "prefer-object-spread": "error",
      "prefer-promise-reject-errors": "error",
      "prefer-regex-literals": "error",
      "prefer-rest-params": "error",
      "prefer-spread": "error",
      "prefer-template": "error",
      "quotes": ["error", "double"],
      "quote-props": ["error", "consistent"],
      "radix": "error",
      "react/boolean-prop-naming": "error",
      "react/button-has-type": "error",
      "react/default-props-match-prop-types": "off",
      "react/destructuring-assignment": "off",
      "react/forbid-component-props": "off",
      "react/forbid-dom-props": "error",
      "react/forbid-elements": "error",
      "react/forbid-foreign-prop-types": "error",
      "react/forbid-prop-types": "off",
      "react/function-component-definition": "error",
      "react/hook-use-state": "error",
      "react-hooks/exhaustive-deps": "off",
      "react-hooks/rules-of-hooks": "off",
      "react/iframe-missing-sandbox": "error",
      "react/jsx-boolean-value": "error",
      "react/jsx-child-element-spacing": "error",
      "react/jsx-closing-bracket-location": "error",
      "react/jsx-closing-tag-location": "error",
      "react/jsx-curly-brace-presence": "error",
      "react/jsx-curly-newline": "off",
      "react/jsx-curly-spacing": "error",
      "react/jsx-equals-spacing": "error",
      "react/jsx-filename-extension": "error",
      "react/jsx-first-prop-new-line": "error",
      "react/jsx-fragments": "error",
      "react/jsx-handler-names": "off",
      "react/jsx-indent": ["error", 2],
      "react/jsx-indent-props": ["error", 2],
      "react/jsx-max-depth": "error",
      "react/jsx-max-props-per-line": "error",
      "react/jsx-newline": "off",
      "react/jsx-no-bind": "error",
      "react/jsx-no-constructed-context-values": "error",
      "react/jsx-no-leaked-render": "off",
      "react/jsx-no-literals": "error",
      "react/jsx-no-script-url": "error",
      "react/jsx-no-useless-fragment": "error",
      "react/jsx-one-expression-per-line": "error",
      "react/jsx-pascal-case": "error",
      "react/jsx-props-no-multi-spaces": "error",
      "react/jsx-props-no-spreading": "off",
      "react/sort-default-props": "error",
      "react/jsx-sort-props": ["error", {ignoreCase: true}],
      "react/jsx-tag-spacing": "error",
      "react/jsx-wrap-multilines": "off",
      "react/jsx-max-props-per-line": "off",
      "react/no-access-state-in-setstate": "error",
      "react/no-adjacent-inline-elements": "error",
      "react/no-array-index-key": "error",
      "react/no-arrow-function-lifecycle": "error",
      "react/no-danger": "error",
      "react/no-did-mount-set-state": "error",
      "react/no-did-update-set-state": "error",
      "react/no-invalid-html-attribute": "error",
      "react/no-multi-comp": "error",
      "react/no-namespace": "error",
      "react/no-redundant-should-component-update": "error",
      "react/no-set-state": "off",
      "react/no-this-in-sfc": "error",
      "react/no-typos": "error",
      "react/no-unstable-nested-components": "error",
      "react/no-unused-class-component-methods": "off",
      "react/no-unused-prop-types": "error",
      "react/no-unused-state": "error",
      "react/no-will-update-set-state": "error",
      "react/prefer-es6-class": "error",
      "react/prefer-exact-props": "error",
      "react/prefer-read-only-props": "error",
      "react/prefer-stateless-function": "error",
      "react/prop-types": "off", // Disabled because it doesn't work with propTypesExact
      "react/require-default-props": "off",
      "react/require-optimization": "error",
      "react/self-closing-comp": "error",
      "react/sort-comp": "off",
      "react/sort-prop-types": "error",
      "react/state-in-constructor": "off",
      "react/static-property-placement": "error",
      "react/style-prop-object": "error",
      "react/void-dom-elements-no-children": "error",
      "require-atomic-updates": "error",
      "rest-spread-spacing": "error",
      "semi": ["error", "never"],
      "semi-spacing": "error",
      "semi-style": "error",
      "sort-imports": "error",
      "sort-vars": "error",
      "space-before-blocks": "error",
      "space-before-function-paren": "off",
      "space-in-parens": "error",
      "space-infix-ops": "error",
      "space-unary-ops": "error",
      "strict": "error",
      "switch-colon-spacing": "error",
      "symbol-description": "error",
      "template-curly-spacing": "error",
      "template-tag-spacing": "error",
      "unicode-bom": "error",
      "vars-on-top": "error",
      "wrap-iife": "error",
      "wrap-regex": "error",
      "yield-star-spacing": "error",
      "yoda": "error",

      // TODO: Configure, fix offences for and enable these
      "array-element-newline": "off", // eslint-disable sort-keys
      "camelcase": "off",
      "capitalized-comments": "off",
      "func-names": "off",
      "id-length": "off",
      "jest/consistent-test-it": "off",
      "jest/prefer-called-with": "off",
      "jest/prefer-expect-assertions": "off",
      "jest/prefer-hooks-in-order": "error",
      "jest/prefer-strict-equal": "off",
      "no-shadow": "off",
      "jest/prefer-to-have-length": "off",
      "max-len": ["error", {"code": 160}],
      "max-lines": "off",
      "max-lines-per-function": "off",
      "max-statements": "off",
      "multiline-comment-style": "off",
      "no-console": "off",
      "no-empty-function": "off",
      "no-extend-native": "off",
      "no-magic-numbers": "off",
      "no-undefined": "off",
      "no-underscore-dangle": "off",
      "no-var": "off",
      "object-property-newline": "off",
      "one-var": "off",
      "prefer-const": "off",
      "prefer-destructuring": "off",
      "prefer-named-capture-group": "off",
      "require-await": "off",
      "require-unicode-regexp": "off",
      "sort-keys": "off",
      "spaced-comment": "off"
    }
  }
])
