export_i18n_js: false
translations:
  - file: "app/javascript/shared/translations.js"
    only: ["*.activerecord.attributes.*", "*.activerecord.models.*", "*.date.*", "*.js.*", "*.number.currency.*", "*.number.format", "*.time.*"]
